
# Docker Compose for running Jenkins

services:
  
  # The jenkins service
  jenkins: 
    image: jenkins-image
    container_name: jenkins-container
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      

volumes:
  jenkins-data: